name: OpenWrt-CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: init
      run: |
        sudo -E apt-get -y install  curl
        ifconfig
        ip addr
        curl ipinfo.io
        curl ky.eesing.com
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
